const Constants = {
    INSTAGRAM_ACCESS_TOKEN: 'EAAe4ZCucnWO8BOZCZA1GRQybzybHKQ4zMnmQEy2eDQSlYuimVtifpyNku6gWLS4tnwlVfe8ngkWZAnp6a9w5N8pMojyMo9XqDj68VdmZBsZAJo0GQml8XibHjY6d5mSZBL2C4JbBrkxX1GLj9U0mlmkrkQmyPrqrGQZBeMKtuK4TaFqGDXwN9ZBEBSZAzfEB6kKJzS',
    INSTAGRAM_API_URL: 'https://graph.instagram.com',
    INSTAGRAM_BUSINESS_ACCOUNT_ID: '17841446625593303',
    GOOGLE_DRIVE_FOLDER_ID: 'YOUR_GOOGLE_DRIVE_FOLDER_ID'
  };
  
  export default Constants;
